name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          DOCKER_IMAGE=sbeck14/crasher
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}
          
          echo $BRANCH
          
          # Add latest and release-# tag on push to master
          if [[ "$BRANCH" = "master" ]]; then
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:release-${GITHUB_RUN_NUMBER}"
          fi
          
          # Add branch-# and shortref tags on push to any branch
          TAGS="$TAGS,${DOCKER_IMAGE}:$BRANCH-${GITHUB_RUN_NUMBER},${DOCKER_IMAGE}:${SHORTREF}"
          
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
