name: test_branch_name

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          
          DOCKER_IMAGE=sbeck14/crasher
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}
          
          # Add latest and release-# tag on push to master
          if [[ "$BRANCH" = "master" ]]; then
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:release-${GITHUB_RUN_NUMBER}"
          fi
          
          # Add branch-# and shortref tags
          TAGS="$TAGS,${DOCKER_IMAGE}:$BRANCH-${GITHUB_RUN_NUMBER},${DOCKER_IMAGE}:${SHORTREF}"
          
          echo "branch is: $BRANCH"
          echo "base ref is $GITHUB_BASE_REF"
          echo "head ref is $GITHUB_HEAD_REF"
          echo ""
          echo "$TAGS"
